#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from galru.GalruCreateSpecies import GalruCreateSpecies

version = ''
try:
	version = pkg_resources.get_distribution("galru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Given a species name, create a database',
	usage = 'galru_create_database [options] "species"'
    , formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('species', help='Species in quotes',  type=str)

parser.add_argument('--output_directory', '-o', help='Output directory, defaults to species name in current directory', type=str)
parser.add_argument('--threads', '-t',  help='No. of threads to use', type=int, default=1)

parser.add_argument('--cdhit_seq_identity', '-i',  help='Sequence identity for CD-hit', type=float, default=0.99)
parser.add_argument('--allow_missing_st', '-a', action='store_true', help='Use files with missing ST [%(default)s]', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on debugging [%(default)s]', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = GalruCreateSpecies(options)
g.run()

