#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from galru.GalruCreateCas import GalruCreateCas

version = ''
try:
	version = pkg_resources.get_distribution("galru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Create Cas gene file',
	usage = 'galru_create [options] output_filename.fa assembly1.fa assembly2.fa'
    , formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('output_filename', help='Output filename for the Cas FASTA file', type=str)
parser.add_argument('input_files', help='Input FASTA files (optionally gzipped)', nargs='+', type=str)

parser.add_argument('--verbose', '-v', action='store_true', help='Turn on debugging [%(default)s]', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = GalruCreateCas(options)
g.run()
