#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from galru.GalruCreateDatabase import GalruCreateDatabase

version = ''
try:
	version = pkg_resources.get_distribution("galru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Create database',
	usage = 'galru_create_database [options] directory assembly1.fa assembly2.fa'
    , formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('output_directory', help='Output directory', type=str)
parser.add_argument('input_files', help='Input FASTA files (optionally gzipped)', nargs='+', type=str)
parser.add_argument('--threads', '-t',  help='No. of threads to use', type=int, default=1)

parser.add_argument('--verbose', '-v', action='store_true', help='Turn on debugging [%(default)s]', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = GalruCreateDatabase(options)
g.run()

